Non-negative Matrix Factorization (NMF) is a useful technique for dimensionality reduction and has applications in recommendation systems. 

NMF is a group of algorithms in multivariate analysis and linear algebra where a matrix 
𝑉 is factorized into (usually) two matrices 𝑊 and 𝐻, with the property that all three matrices have no negative elements. This factorization is useful in the context of recommendation systems because it can help to identify the underlying structure of user-item interactions.

Example: Movie Recommendation System
Let's consider a simple example using movie ratings data. We'll use a small dataset to demonstrate how NMF can be used to predict user preferences.

1. Step-by-Step Implementation
2. Import Libraries
3. Create a Sample Data Matrix
4. Apply NMF
5. Make Predictions

In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import NMF
from sklearn.metrics import mean_squared_error

# Create a small matrix where rows represent users and columns represent movies. 
# The entries are ratings given by users to the movies.
data = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4],
])

# Convert to DataFrame for better visualization
df = pd.DataFrame(data, columns=['Movie1', 'Movie2', 'Movie3', 'Movie4'], index=['User1', 'User2', 'User3', 'User4', 'User5'])
print("Original Ratings Matrix:")
print(df)


Original Ratings Matrix:
       Movie1  Movie2  Movie3  Movie4
User1       5       3       0       1
User2       4       0       0       1
User3       1       1       0       5
User4       1       0       0       4
User5       0       1       5       4


In [2]:
# Apply NMF
# We'll factorize the matrix into two matrices 𝑊 and 𝐻 using NMF.
# Set the number of components (latent features)

# Matrix 𝑊 is known as the user-feature matrix. Each row in 
# 𝑊 represents a user, and each column represents a latent feature. The elements of 
# 𝑊 indicate the strength of the association between users and these latent features.
# each row corresponds to a user, and each column corresponds to a latent feature. 
# The values indicate how strongly a user is associated with each latent feature.

# Matrix 𝐻 is known as the feature-movie matrix. Each row in 
# 𝐻 represents a latent feature, and each column represents a movie. The elements of 
# 𝐻 indicate the strength of the association between latent features and movies.
# each row corresponds to a latent feature, and each column corresponds to a movie. 
# The values indicate how strongly each latent feature is associated with each movie.

# Interpreting the Matrices
# Matrix 𝑊: User-Feature Associations: Each user is represented as a combination of latent features. 
# For instance, User1 has certain associations with the two latent features.
# Matrix 𝐻: Feature-Movie Associations: Each movie is represented as a combination of latent features. 
# For instance, Movie1 has certain associations with the two latent features.

n_components = 2

# Initialize the NMF model
model = NMF(n_components=n_components, init='random', random_state=42)

# Fit the model to the data
W = model.fit_transform(data)
H = model.components_

print("User-Feature Matrix (W):")
print(W)

print("Feature-Movie Matrix (H):")
print(H)


User-Feature Matrix (W):
[[3.56439707 0.        ]
 [2.37654951 0.        ]
 [0.89050141 1.23178233]
 [0.66556354 0.96517217]
 [0.         1.79451388]]
Feature-Movie Matrix (H):
[[1.47452258 0.55917555 0.         0.40826028]
 [0.         0.36226565 1.58270795 2.90831012]]


In [3]:
# To predict the missing values in the original matrix, we multiply 
# 𝑊 and 𝐻 to reconstruct the approximate original matrix:
# 𝑉 ≈ 𝑊 × 𝐻

# Make predictions
# Reconstruct the original matrix
reconstructed_matrix = np.dot(W, H)

# Convert to DataFrame for better visualization
reconstructed_df = pd.DataFrame(reconstructed_matrix, columns=['Movie1', 'Movie2', 'Movie3', 'Movie4'], index=['User1', 'User2', 'User3', 'User4', 'User5'])
print("Reconstructed Ratings Matrix:")
print(reconstructed_df)

# Calculate the reconstruction error
error = mean_squared_error(data, reconstructed_matrix)
print(f"Reconstruction Error: {error}")


Reconstructed Ratings Matrix:
         Movie1    Movie2    Movie3    Movie4
User1  5.255784  1.993124  0.000000  1.455202
User2  3.504276  1.328908  0.000000  0.970251
User3  1.313064  0.944179  1.949552  3.945961
User4  0.981388  0.721816  1.527586  3.078743
User5  0.000000  0.650091  2.840191  5.219003
Reconstruction Error: 0.9144353703891276


Possible Interpretations of Latent Features
Genre Preferences

Feature 1: May correspond to a preference for action movies.
Feature 2: May correspond to a preference for romantic comedies.
Each user and movie can have varying degrees of association with these genres. For example, a user who prefers action movies will have a higher value for Feature 1 in their 
𝑊
W matrix representation.
Movie Themes

Feature 1: May represent a preference for movies with strong heroic themes.
Feature 2: May represent a preference for movies with complex storylines.
Users who enjoy heroic themes will have higher weights for Feature 1, and movies with these themes will also have higher weights for Feature 1 in the 
𝐻
H matrix.
Directorial Styles

Feature 1: May reflect a liking for movies directed by certain directors known for a specific style.
Feature 2: May reflect a liking for movies with a unique visual style.
Users and movies can be associated with these styles, indicating preferences for certain directors or visual elements.
Actor Preferences

Feature 1: May represent a preference for movies featuring a particular actor or set of actors.
Feature 2: May represent a preference for ensemble casts.
Users who prefer movies with certain actors will have higher weights for the corresponding feature.
Movie Length or Complexity

Feature 1: May indicate a preference for shorter, simpler movies.
Feature 2: May indicate a preference for longer, more complex movies.
Users and movies are categorized based on the length and complexity, with higher weights for the preferred type.

In [4]:
# User-Feature Matrix (W):
[[0.50712611 1.73855016]  # User1 prefers critically acclaimed, story-driven movies
 [0.34179519 1.31863799]  # User2 has a slight preference for story-driven movies
 [2.23307829 0.01402468]  # User3 prefers action-packed, high-budget movies
 [1.78944285 0.00479843]  # User4 strongly prefers action-packed movies
 [0.03515571 1.87399994]] # User5 strongly prefers story-driven movies

# Feature-Movie Matrix (H):
[[0.02886567 0.0128776  1.79073088 1.94308634]  # Feature 1 (Action-packed)
 [2.84933456 1.67911686 0.00785518 0.01622395]] # Feature 2 (Story-driven)


SyntaxError: invalid syntax (2551803083.py, line 1)

Interpretation
Movie1: Low values in both features, might be a documentary or a niche genre.
Movie2: Low values in both features, similar to Movie1.
Movie3: High value in Feature 1, suggesting it's an action-packed, high-budget movie.
Movie4: High value in Feature 1, also suggesting it's an action-packed movie.
Using These Interpretations
When making recommendations:

For User1 (story-driven preference): Movies like Movie4 (high in Feature 2) would be recommended.
For User3 (action-packed preference): Movies like Movie3 and Movie4 (high in Feature 1) would be recommended.
Summary
Latent features in NMF capture hidden patterns in the data that influence user preferences and item characteristics. These features can represent various abstract concepts like genres, themes, directorial styles, or other attributes that aren't directly labeled in the dataset. By interpreting these features, we can better understand user preferences and make more accurate recommendations.